### ISSUE TITLE
the test result is poor

### ISSUE THREAD

**Issue by Gaochunyang12345** [Bingwen-Hu/ERGAN-Pytorch#1]
Hi , tks for your beautiful job. While test a image to remove the glasses ,I got a very poor result.
![swap](https://user-images.githubusercontent.com/50621508/70038409-20d09c00-15f3-11ea-84ee-87ca91fbae97.jpg)

**Comment by Bingwen-Hu** [comment]
Hi, @Gaochunyang12345 , 
The main reason for the pool result is that the image does not align well.  We just set the eye area according to the CelebA dataset. If you want to obtain a better result on your own datasets, you should set a suitable eye area,  and then train from scratch.
