### ISSUE TITLE
Can't get a good result

### ISSUE THREAD

**Issue by Timmy0425** [Bingwen-Hu/ERGAN-Pytorch#2]
Hello, thanks for your wonderful work. 
I want to test on MeGlass dataset, but I got the result likes the following picture.
I also test on CelebA dataset from Google Drive that you provide. The results are similar to the one of MeGlass.
Did I do any wrong?

I typed this command to get the testing result:
`python test_batch.py --config configs/celeba.yaml --A MeGlass/probe_glass --B MeGlass/probe_no_glass --output_folder results/celeba --checkpoint models/celeba.pt`

![image](https://user-images.githubusercontent.com/36808249/75244689-3840af00-5807-11ea-96ca-e6575d26d7f0.png)

**Comment by Bingwen-Hu** [comment]
Hi,
Thanks for your interest in our work.
The pre-trained model we provided was trained on the CelebA dataset. If you want to use the pre-trained model to process other data (such as LFW, Meglass), you need to adjust the size of the eye area according to the shape of the input image, and then fine-tune the model to get better results.
