### ISSUE TITLE
Fine tune on Meglass

### ISSUE THREAD

**Issue by Timmy0425** [Bingwen-Hu/ERGAN-Pytorch#3]
Hello

I adjusted the eye area and tried to fine tune on meglass and LFW. But there is a problem that only the pretrained generator model is available but no discriminator and optimizer. So, I can't fine tune on it. 
Could you release the pretrained models of discriminator and optimizer?
Or it'll be best if you give me the pre-trained model on Meglass and LFW!  :)

Thank you very much!

**Comment by Bingwen-Hu** [comment]
Hi Timmy0425,
I have updated 'README.MD'. Please see it for details.

**Comment by Timmy0425** [comment]
Thank you very much!
