### ISSUE TITLE
test checkpoint file

### ISSUE THREAD

**Issue by mirishtaif** [Bingwen-Hu/ERGAN-Pytorch#5]
Hi,
Thanks for sharing your code!
I tried to train it on my own data but I am not getting the celeba.pt file that you have in your pre-trained model (for the test part). Where is it generated? Do I need to add any flag for it?

thanks,
Miri

**Comment by Bingwen-Hu** [comment]
Hi, please check this function https://github.com/Bingwen-Hu/ERGAN-Pytorch/blob/0abf184ef5b744e9d8b192fc85fb050c16e43a9e/trainer.py#L299

**Comment by mirishtaif** [comment]
Hi, thanks.
So the file celeba.pt is the optimizer?

**Comment by Bingwen-Hu** [comment]
No, the snapshot checkpoints files include generator: 'gen_%08d.pt' ,  discriminator: 'dis_%08d.pt' , and optimizer :'optimizer.pt'. In training, all of those should be saved. However,  if you want to test a well-trained model, only 'gen_%08d.pt' checkpoints are required. In our case, the pre-trained model is specific to the CelebA dataset, so we rename it to 'celeba.pt' ('gen_%08d.pt' ->  'celeba.pt' ). Note that 'celeba.pt' only includes checkpoints for the generator.
